title: Kamil Eliaszuk # your name (or website title) here
logo: "/images/photo_edited.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a Technical / Computer Physics student of Warsaw University of Technology. Ambitious, motivated and constantly learning.
  I'm mostly interested in programming and data science and looking for experience in that field. Previously I had an internship at CERN.
  <br><br>
  <a href="https://www.linkedin.com/in/kamil-eliaszuk-ab2473238/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
